FROM python:3.13-slim

WORKDIR /app

# Копіюємо саме ЛЕГКИЙ файл залежностей
COPY requirements-scraper.txt requirements.txt

# Встановлюємо залежності для скрапера (забере 5-10 секунд)
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо код проєкту
COPY src/ ./src/

ENV PYTHONUNBUFFERED=1

CMD ["python", "src/scraper/scraper_worker.py"]